name: NY-Euler Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  nix-ci:
    runs-on: x86_64-linux
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/cachix-action@v15
        with:
          name: nammayatri
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          skipPush: true

      - name: Build all flake outputs
        run: om ci
