{-# LANGUAGE AllowAmbiguousTypes #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE StandaloneDeriving #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# OPTIONS_GHC -Wno-orphans -Wno-missing-signatures #-}

-- =============================================================================
-- The test table, defined EXACTLY the way a Namma Yatri Storage.Beam module is:
-- a Beam record, its Table/PrimaryKey instance, a ModelMeta with the snake_case
-- SQL column mapping, and ONE splice that KV-enables it. Everything KV needs
-- (KVConnector, MeshMeta Postgres, ToJSON/FromJSON, Serialize) is generated by
-- `enableKVPG` — see KvConnectorTH.
--
-- Table `kv_live`:
--   id         text  PRIMARY KEY
--   group_id   text  (secondary index #1)
--   status     text  (secondary index #2)
--   cnt        int
--   note       text  NULL  (Maybe — exercises omitNothingFields / additive merge)
--   updated_at timestamptz (ordering column for findAllWithOptions)
--   payload    text
-- =============================================================================
module Schema where

import Data.Time (UTCTime)
import qualified Database.Beam as B
import EulerHS.KVConnector.Types (TableMappings (..))
import EulerHS.Prelude hiding (id, note)
import KvConnectorTH (enableKVPG)
import Sequelize (ModelMeta (..))

data KvLiveT f = KvLiveT
  { id :: B.C f Text,
    groupId :: B.C f Text,
    status :: B.C f Text,
    cnt :: B.C f Int,
    note :: B.C f (Maybe Text),
    updatedAt :: B.C f UTCTime,
    payload :: B.C f Text
  }
  deriving (Generic, B.Beamable)

instance B.Table KvLiveT where
  data PrimaryKey KvLiveT f = KvLiveId (B.C f Text) deriving (Generic, B.Beamable)
  primaryKey = KvLiveId . id

type KvLive = KvLiveT Identity

deriving instance Show KvLive

deriving instance Eq KvLive

deriving instance Ord KvLive

-- snake_case SQL column mapping (the DB side). The KV/Redis side uses the
-- camelCase ModMesh the macro generates.
kvLiveModSql :: KvLiveT (B.FieldModification (B.TableField KvLiveT))
kvLiveModSql =
  B.tableModification
    { id = B.fieldNamed "id",
      groupId = B.fieldNamed "group_id",
      status = B.fieldNamed "status",
      cnt = B.fieldNamed "cnt",
      note = B.fieldNamed "note",
      updatedAt = B.fieldNamed "updated_at",
      payload = B.fieldNamed "payload"
    }

instance ModelMeta KvLiveT where
  modelFieldModification = kvLiveModSql
  modelTableName = "kv_live"
  modelSchemaName = Nothing

instance TableMappings (KvLiveT Identity) where
  getTableName = "kv_live"
  getTableMappings = []

$(enableKVPG ''KvLiveT ['id] [['groupId], ['status]])
